- { cpu: "ath79", platform: "generic", profile: "tplink_archer-c7-v2" }
- { cpu: "ath79", platform: "nand", profile: "glinet_gl-ar750s-nor" }
- { cpu: "ath79", platform: "nand", profile: "glinet_gl-ar750s-nor-nand" }
- { cpu: "bcm27xx", platform: "bcm2708", profile: "rpi" }
- { cpu: "mvebu", platform: "cortexa9", profile: "linksys_wrt32x" }
- { cpu: "ramips", platform: "mt7621", profile: "glinet_gl-mt1300" }
- { cpu: "x86", platform: "64", profile: "generic" }
