#!/bin/sh /etc/rc.common
if [ "${ACTION}" = "add" ] && [ "${DEVTYPE}" = "partition" ] && mountpoint -q /mnt/${DEVNAME}; then
	if [ -e "/mnt/${DEVNAME}/usbinit.sh" ]; then
		/bin/sh "/mnt/${DEVNAME}/usbinit.sh"
		sync
	fi
fi
